version: '3'
services:
  bot:
    image: "biospheere/weathercloudscraper"
    restart: always
    env_file: .env
    depends_on:
    - db
  db:
    image: mysql:8
    restart: always
    container_name: mysql 
    env_file: .env
    volumes:
    - mysql-volume:/var/lib/mysql


volumes:
  mysql-volume: