{
 "title": "Weathercloud",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "11m",
 "panels": [
  {
   "title": "Temperature in Boutaresse",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Temperature\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=3914926509\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Temperature in Guignies",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Temperature\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=8148852804\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Temerature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Temperature as Boutaresse\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=3914926509\nORDER BY Timestamp"
    },
    {
     "dataset": "balkans",
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Temperature as Guignies\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=8148852804\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Humidity in Boutaresse",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Humidty\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=3914926509\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Humidity in Guignies",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Humidty\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=8148852804\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Humidty as Boutaresse\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=3914926509\nORDER BY Timestamp"
    },
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Humidty as Guignies\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=8148852804\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Atmospheric pressure in Boutaresse",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Bar\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=3914926509\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Atmospheric pressure in Guignies",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Bar\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=8148852804\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Atmospheric pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Bar as Boutaresse\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=3914926509\nORDER BY Timestamp"
    },
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Bar as Guignies\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=8148852804\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Rain in Boutaresse",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Rain\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=3914926509\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Rain in Guignies",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Rain\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=8148852804\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Rain Distribution",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Rain as Boutaresse\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=3914926509\nORDER BY Timestamp"
    },
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Rain as Guignies\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=8148852804\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Windchill in Boutaresse",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Windchill\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=3914926509\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Windchill in Guignies",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Windchill\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=8148852804\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Wind speed and gust",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Windspeed*3.6 as Boutaresse\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=3914926509\nORDER BY Timestamp"
    },
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Windspeed*3.6 as Guignies\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=8148852804\nORDER BY Timestamp"
    },
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Gust*3.6 as Boutaresse_gust\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=3914926509\nORDER BY Timestamp"
    },
    {
     "rawSql": "SELECT\n  Timestamp AS \"time\",\n  Gust*3.6 as Guignies_gust\nFROM Weather\nWHERE\n  $__timeFilter(Timestamp) and Device=8148852804\nORDER BY Timestamp"
    }
   ]
  },
  {
   "title": "Winds in Boutaresse",
   "type": "operato-windrose-panel",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 30 },
   "targets": [
    {
     "dataset": "weathercloud",
     "rawSql": "SELECT \n    ROUND(Windspeed*3.6, 0) AS wind_speed, \n    Winddirection AS wind_direction\nFROM Weather WHERE Device = 3914926509 and  $__timeFilter(Timestamp)"
    }
   ]
  },
  {
   "title": "Winds in Guignies",
   "type": "operato-windrose-panel",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 30 },
   "targets": [
    {
     "dataset": "weathercloud",
     "rawSql": "SELECT \n    ROUND(Windspeed*3.6, 0) AS wind_speed, \n    Winddirection AS wind_direction\nFROM Weather WHERE Device = 8148852804 and  $__timeFilter(Timestamp)"
    }
   ]
  }
 ]
}