version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    environment:
      - DATABASE_PASSWORD=123456
      - DATABASE_USER=root
      - DATABASE_HOST=mysql

    container_name: WeathercloudScraper
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
  db:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=WeathercloudScraper
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume: